name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7]

    steps:
    - uses: actions/checkout@v1
    - name: set up python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: install dependencies
      run: |
        pip install --upgrade pip
        python -m pip install pipenv
        pipenv --python $(which python${{ matrix.python-version }}) install --dev
    - name: lint
      run: make lint
    - name: test
      run: make test
